spring.application.name=emailwarmup

server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/emailwarmup}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

security.jwt.secret=${SECURITY_JWT_SECRET:Q29kZXhFbWFpbFdhcm11cFRlbXBTZWNyZXRLZXlGb3JERXZlbG9wbWVudDIwMjY=}
security.jwt.expiration-ms=${SECURITY_JWT_EXPIRATION_MS:3600000}

security.crypto.secret=${SECURITY_CRYPTO_SECRET:change-me-please-use-strong-secret}
sender.smtp.test-timeout-ms=${SENDER_SMTP_TEST_TIMEOUT_MS:10000}
